{% set name = "vizent" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vizent-{{ version }}.tar.gz
  sha256: efca9278ac602335718764604ffdbb004bbc357a9286ec620fe7fba7cb6c58db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - vizent
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://cusplondon.ac.uk/vizent
  summary: A python library for visualising bivariate data using glyphs and node-link diagrams with matplotlib.
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/cusp-london/vizent

extra:
  recipe-maintainers:
    - peterbaudains
